[package]
name = "teamcity"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
lazy_static = "1.4.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
git2 = "0.15"
arboard = "3.2.0"
clap = { version = "4.0.29", features = ["derive", "env"] }
clap_complete = "4.0.6"
console = "0.15.2"
prettytable-rs = "^0.9"
chrono = "0.4.23"
skim = "*"
struct-field-names-as-array = "0.1.4"
config = "0.13.1"
xdg = "^2.1"
anyhow = "1.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
